name: Deploy PowerShell to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Pages content
        run: |
            mkdir public

            REDIRECT_HTML='<# <!DOCTYPE html><html><head><meta http-equiv="refresh" content="0;url=https://hira.im"><script>window.location.replace("https://hira.im")</script></head><body>Redirecting to <a href="https://hira.im">hira.im</a>...</body></html> #>'

            echo "$REDIRECT_HTML" | cat - index.ps1 > public/index.html
            echo "$REDIRECT_HTML" | cat - Get-Appx.ps1 > public/AppInstaller

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4